CREATE DATABASE IF NOT EXISTS assign3;
USE assign3;
CREATE TABLE marks(
sid INT PRIMARY KEY AUTO_INCREMENT,
sname VARCHAR(50) NOT NULL,
marks1 INT NOT NULL,
marks2 INT NOT NULL,
marks3 INT NOT NULL
);